kind = "mobile"
previewPath = "/"
title = "Chip Society-Build"
version = "1.0.0"
id = "artifacts/neon-river"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22743

[services.development]
run = "pnpm --filter @workspace/neon-river run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/neon-river", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/neon-river", "run", "serve" ]

[services.env]
PORT = "22743"
BASE_PATH = "/"
