import type { GameVariant } from './gameVariants';

export type TournamentType =
  | 'beginner' | 'sitandgo' | 'turbo' | 'daily' | 'highroller'
  | 'nightgrind' | 'weekendmajor' | 'deepstack' | 'hyperturbo'
  | 'sd_lounge' | 'sd_showdown' | 'sd_rush' | 'sd_royal'
  | 'omaha_championship' | 'omaha_highroller'
  | 'joker_showdown' | 'joker_jackpot';

export interface VariantBadge {
  icon: string;
  label: string;
  symbol: string;
  color: string;
}

export const VARIANT_BADGES: Record<GameVariant, VariantBadge> = {
  texas_holdem:      { icon: 'diamond-outline',   label: "HOLD'EM",    symbol: '♠',  color: '#00d4ff' },
  short_deck_holdem: { icon: 'layers-outline',    label: 'SHORT DECK', symbol: '6+', color: '#bf5fff' },
  omaha_holdem:      { icon: 'apps-outline',      label: 'OMAHA',      symbol: '🂠', color: '#7c3aed' },
  joker_holdem:      { icon: 'sparkles-outline',  label: 'JOKER',      symbol: '🃏', color: '#22c55e' },
};

export function getVariantBadge(variant: GameVariant): VariantBadge {
  return VARIANT_BADGES[variant];
}

export interface BlindLevel {
  sb: number;
  bb: number;
}

export interface TournamentConfig {
  type: TournamentType;
  name: string;
  subtitle: string;
  description: string;
  buyIn: number;
  startingChips: number;
  numPlayers: 4 | 5 | 6;
  handsPerLevel: number;
  blindSchedule: BlindLevel[];
  estimatedDuration: string;
  targetPlayer: string;
  color: string;
  icon: string;
  emoji: string;
  format: string;
  prizeLabel: string;
  variant: GameVariant;
  capacityMax: number;
  scheduleIntervalMin: number;
  scheduleOffsetMin: number;
}

export const TOURNAMENT_CONFIGS: Record<TournamentType, TournamentConfig> = {
  beginner: {
    type: 'beginner',
    name: 'LOW STAKES LOUNGE',
    subtitle: '5 players · Entry level',
    description: 'Beginner-friendly poker. Deep stacks and slow blinds leave plenty of room for post-flop play while you learn the ropes.',
    buyIn: 5_000,
    startingChips: 10_000,
    numPlayers: 5,
    handsPerLevel: 5,
    blindSchedule: [
      { sb: 25, bb: 50 }, { sb: 50, bb: 100 }, { sb: 75, bb: 150 },
      { sb: 100, bb: 200 }, { sb: 150, bb: 300 }, { sb: 200, bb: 400 },
      { sb: 300, bb: 600 }, { sb: 400, bb: 800 },
    ],
    estimatedDuration: '25–35 min',
    targetPlayer: 'New & casual players',
    color: '#00d4ff',
    icon: 'disc-outline',
    emoji: '🎰',
    format: 'Freezeout · Slow Blinds',
    prizeLabel: '1st: 70%  ·  2nd: 30%',
    variant: 'texas_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 15,
    scheduleOffsetMin: 0,
  },
  sitandgo: {
    type: 'sitandgo',
    name: 'SIT & GO RUSH',
    subtitle: '5 players · Starts instantly',
    description: 'Single-table tournament that starts the moment seats fill. Shorter stacks and a brisk clock mean every decision matters.',
    buyIn: 15_000,
    startingChips: 7_500,
    numPlayers: 5,
    handsPerLevel: 3,
    blindSchedule: [
      { sb: 50, bb: 100 }, { sb: 100, bb: 200 }, { sb: 150, bb: 300 },
      { sb: 250, bb: 500 }, { sb: 400, bb: 800 }, { sb: 600, bb: 1200 },
      { sb: 900, bb: 1800 },
    ],
    estimatedDuration: '12–18 min',
    targetPlayer: 'Players who want a quick, complete game',
    color: '#00e887',
    icon: 'flash-outline',
    emoji: '⚡',
    format: 'Freezeout · Starts Instantly',
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'texas_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 30,
    scheduleOffsetMin: 7,
  },
  turbo: {
    type: 'turbo',
    name: 'TURBO HEAT',
    subtitle: '5 players · Fast blinds',
    description: 'Short stacks and rapid blind jumps force constant all-in decisions. Built for high-action, low-patience poker.',
    buyIn: 25_000,
    startingChips: 5_000,
    numPlayers: 5,
    handsPerLevel: 3,
    blindSchedule: [
      { sb: 100, bb: 200 }, { sb: 200, bb: 400 }, { sb: 400, bb: 800 },
      { sb: 800, bb: 1600 }, { sb: 1600, bb: 3200 }, { sb: 3200, bb: 6400 },
    ],
    estimatedDuration: '8–12 min',
    targetPlayer: 'Action players who love short stacks',
    color: '#ff6600',
    icon: 'speedometer-outline',
    emoji: '🔥',
    format: 'Turbo · Fast Blind Levels',
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'texas_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 45,
    scheduleOffsetMin: 18,
  },
  daily: {
    type: 'daily',
    name: 'DAILY CHAMPIONSHIP',
    subtitle: '5 players · Main daily event',
    description: 'The balanced flagship event. Enough depth for real strategy, paced to finish inside an hour — the best all-around tournament.',
    buyIn: 100_000,
    startingChips: 20_000,
    numPlayers: 5,
    handsPerLevel: 6,
    blindSchedule: [
      { sb: 50, bb: 100 }, { sb: 75, bb: 150 }, { sb: 100, bb: 200 },
      { sb: 150, bb: 300 }, { sb: 250, bb: 500 }, { sb: 400, bb: 800 },
      { sb: 600, bb: 1200 }, { sb: 900, bb: 1800 },
    ],
    estimatedDuration: '45–60 min',
    targetPlayer: 'Players who want deep, balanced poker',
    color: '#00ff88',
    icon: 'ribbon-outline',
    emoji: '🏅',
    format: 'Freezeout · Balanced Structure',
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'texas_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 60,
    scheduleOffsetMin: 27,
  },
  highroller: {
    type: 'highroller',
    name: 'HIGH ROLLER',
    subtitle: '5 players · Elite stakes',
    description: 'The biggest buy-in among the standard events. Deep stacks, patient blind growth, and the biggest prizes for elite players.',
    buyIn: 500_000,
    startingChips: 30_000,
    numPlayers: 5,
    handsPerLevel: 7,
    blindSchedule: [
      { sb: 100, bb: 200 }, { sb: 150, bb: 300 }, { sb: 200, bb: 400 },
      { sb: 300, bb: 600 }, { sb: 400, bb: 800 }, { sb: 600, bb: 1200 },
      { sb: 800, bb: 1600 }, { sb: 1200, bb: 2400 },
    ],
    estimatedDuration: '60–90 min',
    targetPlayer: 'Elite players chasing prestige',
    color: '#ffd700',
    icon: 'diamond-outline',
    emoji: '👑',
    format: 'Deep Stack · VIP Entry',
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'texas_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 90,
    scheduleOffsetMin: 34,
  },
  nightgrind: {
    type: 'nightgrind',
    name: 'NIGHT GRIND',
    subtitle: '5 players · Long-form patience',
    description: 'Very slow blind growth rewards patience over aggression. A long, grinding tournament for players who want real poker.',
    buyIn: 250_000,
    startingChips: 25_000,
    numPlayers: 5,
    handsPerLevel: 9,
    blindSchedule: [
      { sb: 25, bb: 50 }, { sb: 50, bb: 100 }, { sb: 75, bb: 150 },
      { sb: 100, bb: 200 }, { sb: 150, bb: 300 }, { sb: 200, bb: 400 },
      { sb: 300, bb: 600 }, { sb: 400, bb: 800 }, { sb: 600, bb: 1200 },
    ],
    estimatedDuration: '75+ min',
    targetPlayer: 'Patient, long-form grinders',
    color: '#8855ff',
    icon: 'moon-outline',
    emoji: '🌙',
    format: 'Deep Stack · Very Slow Blinds',
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'texas_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 120,
    scheduleOffsetMin: 55,
  },
  weekendmajor: {
    type: 'weekendmajor',
    name: 'WEEKEND MAJOR',
    subtitle: '5 players · Premium featured event',
    description: 'The largest featured event on the schedule. Massive prize pool, deep stacks, and the most prestige of any tournament.',
    buyIn: 1_000_000,
    startingChips: 50_000,
    numPlayers: 5,
    handsPerLevel: 7,
    blindSchedule: [
      { sb: 100, bb: 200 }, { sb: 150, bb: 300 }, { sb: 200, bb: 400 },
      { sb: 300, bb: 600 }, { sb: 400, bb: 800 }, { sb: 600, bb: 1200 },
      { sb: 900, bb: 1800 }, { sb: 1300, bb: 2600 },
    ],
    estimatedDuration: '90–120 min',
    targetPlayer: 'High rollers chasing the biggest prize',
    color: '#ff0090',
    icon: 'trophy-outline',
    emoji: '🏆',
    format: 'Deep Stack · Featured Event',
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'texas_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 180,
    scheduleOffsetMin: 90,
  },
  deepstack: {
    type: 'deepstack',
    name: 'DEEP STACK CLASSIC',
    subtitle: '5 players · Professional structure',
    description: 'The longest, deepest structure available. Minimal luck, maximum skill — built for professional-style poker.',
    buyIn: 250_000,
    startingChips: 50_000,
    numPlayers: 5,
    handsPerLevel: 9,
    blindSchedule: [
      { sb: 25, bb: 50 }, { sb: 50, bb: 100 }, { sb: 75, bb: 150 },
      { sb: 100, bb: 200 }, { sb: 150, bb: 300 }, { sb: 200, bb: 400 },
      { sb: 300, bb: 600 }, { sb: 400, bb: 800 }, { sb: 600, bb: 1200 },
    ],
    estimatedDuration: '90+ min',
    targetPlayer: 'Skill-focused, strategic players',
    color: '#00d4ff',
    icon: 'layers-outline',
    emoji: '🎩',
    format: 'Deep Stack · Professional Structure',
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'texas_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 150,
    scheduleOffsetMin: 70,
  },
  hyperturbo: {
    type: 'hyperturbo',
    name: 'HYPER TURBO',
    subtitle: '5 players · Pure chaos',
    description: 'Blinds jump every single hand. Tiny stacks, huge variance, non-stop all-ins — the fastest, wildest tournament on offer.',
    buyIn: 100_000,
    startingChips: 3_000,
    numPlayers: 5,
    handsPerLevel: 1,
    blindSchedule: [
      { sb: 200, bb: 400 }, { sb: 400, bb: 800 }, { sb: 800, bb: 1600 },
      { sb: 1600, bb: 3200 }, { sb: 3200, bb: 6400 }, { sb: 6400, bb: 12800 },
    ],
    estimatedDuration: '5–8 min',
    targetPlayer: 'Thrill-seekers who love chaos',
    color: '#ff2244',
    icon: 'nuclear-outline',
    emoji: '☢️',
    format: 'Hyper Turbo · Blinds Every Hand',
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'texas_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 20,
    scheduleOffsetMin: 9,
  },
  sd_lounge: {
    type: 'sd_lounge',
    name: 'SHORT DECK LOUNGE',
    subtitle: '5 players · 36-card entry',
    description: 'Entry-level Short Deck Hold\'em. Flush beats Full House — 36-card deck, slow blinds, forgiving pacing.',
    buyIn: 5_000,
    startingChips: 10_000,
    numPlayers: 5,
    handsPerLevel: 5,
    blindSchedule: [
      { sb: 20, bb: 40 }, { sb: 40, bb: 80 }, { sb: 60, bb: 120 },
      { sb: 100, bb: 200 }, { sb: 150, bb: 300 }, { sb: 220, bb: 440 },
      { sb: 320, bb: 640 },
    ],
    estimatedDuration: '25–35 min',
    targetPlayer: 'Short Deck beginners',
    color: '#bf5fff',
    icon: 'layers-outline',
    emoji: '🃏',
    format: 'Short Deck · Freezeout',
    prizeLabel: '1st: 70%  ·  2nd: 30%',
    variant: 'short_deck_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 20,
    scheduleOffsetMin: 4,
  },
  sd_showdown: {
    type: 'sd_showdown',
    name: 'SIX PLUS SHOWDOWN',
    subtitle: '5 players · Short Deck NL',
    description: 'Classic Short Deck tournament. 36 cards, elevated hand rankings, moderate pacing.',
    buyIn: 15_000,
    startingChips: 25_000,
    numPlayers: 5,
    handsPerLevel: 4,
    blindSchedule: [
      { sb: 40, bb: 80 }, { sb: 80, bb: 160 }, { sb: 120, bb: 240 },
      { sb: 200, bb: 400 }, { sb: 320, bb: 640 }, { sb: 480, bb: 960 },
    ],
    estimatedDuration: '18–25 min',
    targetPlayer: 'Regular Short Deck players',
    color: '#ff0090',
    icon: 'shuffle-outline',
    emoji: '🎯',
    format: 'Short Deck · Classic Format',
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'short_deck_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 35,
    scheduleOffsetMin: 12,
  },
  sd_rush: {
    type: 'sd_rush',
    name: '36-CARD RUSH',
    subtitle: '5 players · Fast Short Deck',
    description: 'Turbo-paced Short Deck Hold\'em. Rapid blinds and short stacks push maximum action.',
    buyIn: 25_000,
    startingChips: 50_000,
    numPlayers: 5,
    handsPerLevel: 3,
    blindSchedule: [
      { sb: 80, bb: 160 }, { sb: 160, bb: 320 }, { sb: 300, bb: 600 },
      { sb: 550, bb: 1100 }, { sb: 1000, bb: 2000 }, { sb: 1800, bb: 3600 },
    ],
    estimatedDuration: '10–15 min',
    targetPlayer: 'Short Deck action players',
    color: '#ff8800',
    icon: 'flash-outline',
    emoji: '💨',
    format: 'Short Deck · Turbo',
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'short_deck_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 50,
    scheduleOffsetMin: 23,
  },
  sd_royal: {
    type: 'sd_royal',
    name: 'ROYAL SHORT DECK',
    subtitle: '5 players · Premium Short Deck',
    description: 'High-stakes Short Deck Hold\'em for experienced players. Big stacks, slow blinds, maximum prestige.',
    buyIn: 100_000,
    startingChips: 200_000,
    numPlayers: 5,
    handsPerLevel: 8,
    blindSchedule: [
      { sb: 100, bb: 200 }, { sb: 150, bb: 300 }, { sb: 220, bb: 440 },
      { sb: 320, bb: 640 }, { sb: 480, bb: 960 }, { sb: 700, bb: 1400 },
      { sb: 1000, bb: 2000 }, { sb: 1450, bb: 2900 },
    ],
    estimatedDuration: '60–90 min',
    targetPlayer: 'Elite Short Deck players',
    color: '#ffd700',
    icon: 'star-outline',
    emoji: '💎',
    format: 'Short Deck · Deep Stack VIP',
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'short_deck_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 70,
    scheduleOffsetMin: 41,
  },
  omaha_championship: {
    type: 'omaha_championship',
    name: 'OMAHA CHAMPIONSHIP',
    subtitle: '5 players · 4-card action',
    description: 'The flagship Omaha Hold\'em event. Four hole cards, exactly two must be used — huge draws, huge pots, balanced pacing.',
    buyIn: 250_000,
    startingChips: 25_000,
    numPlayers: 5,
    handsPerLevel: 7,
    blindSchedule: [
      { sb: 50, bb: 100 }, { sb: 75, bb: 150 }, { sb: 100, bb: 200 },
      { sb: 150, bb: 300 }, { sb: 250, bb: 500 }, { sb: 400, bb: 800 },
      { sb: 600, bb: 1200 }, { sb: 900, bb: 1800 },
    ],
    estimatedDuration: '60–75 min',
    targetPlayer: 'Omaha regulars chasing big multi-way pots',
    color: '#7c3aed',
    icon: 'apps-outline',
    emoji: '🂠',
    format: "Omaha Hold'em · Freezeout",
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'omaha_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 65,
    scheduleOffsetMin: 15,
  },
  omaha_highroller: {
    type: 'omaha_highroller',
    name: 'OMAHA HIGH ROLLER',
    subtitle: '5 players · Elite 4-card stakes',
    description: 'The biggest Omaha buy-in on offer. Deep stacks, patient blind growth, and massive prizes for elite Omaha specialists.',
    buyIn: 1_000_000,
    startingChips: 40_000,
    numPlayers: 5,
    handsPerLevel: 8,
    blindSchedule: [
      { sb: 100, bb: 200 }, { sb: 150, bb: 300 }, { sb: 200, bb: 400 },
      { sb: 300, bb: 600 }, { sb: 400, bb: 800 }, { sb: 600, bb: 1200 },
      { sb: 800, bb: 1600 }, { sb: 1200, bb: 2400 },
    ],
    estimatedDuration: '~90 min',
    targetPlayer: 'Elite Omaha players chasing the biggest prize',
    color: '#c026d3',
    icon: 'diamond-outline',
    emoji: '💜',
    format: "Omaha Hold'em · Deep Stack VIP",
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'omaha_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 100,
    scheduleOffsetMin: 45,
  },
  joker_showdown: {
    type: 'joker_showdown',
    name: 'JOKER SHOWDOWN',
    subtitle: '5 players · Wild card chaos',
    description: 'Joker Hold\'em with wild Jokers in the deck — Five of a Kind is possible. Fast pacing keeps every hand unpredictable.',
    buyIn: 100_000,
    startingChips: 15_000,
    numPlayers: 5,
    handsPerLevel: 4,
    blindSchedule: [
      { sb: 50, bb: 100 }, { sb: 100, bb: 200 }, { sb: 150, bb: 300 },
      { sb: 250, bb: 500 }, { sb: 400, bb: 800 }, { sb: 600, bb: 1200 },
    ],
    estimatedDuration: '~45 min',
    targetPlayer: 'Players who love wild-card chaos',
    color: '#22c55e',
    icon: 'sparkles-outline',
    emoji: '🃏',
    format: "Joker Hold'em · Wild Cards",
    prizeLabel: '1st: 70%  ·  2nd: 30%',
    variant: 'joker_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 40,
    scheduleOffsetMin: 20,
  },
  joker_jackpot: {
    type: 'joker_jackpot',
    name: 'JOKER JACKPOT',
    subtitle: '5 players · Wild card featured event',
    description: 'The premium Joker Hold\'em event. Wild Jokers, Five of a Kind hands, and a bigger prize pool than Joker Showdown.',
    buyIn: 500_000,
    startingChips: 30_000,
    numPlayers: 5,
    handsPerLevel: 6,
    blindSchedule: [
      { sb: 100, bb: 200 }, { sb: 150, bb: 300 }, { sb: 200, bb: 400 },
      { sb: 300, bb: 600 }, { sb: 450, bb: 900 }, { sb: 700, bb: 1400 },
      { sb: 1000, bb: 2000 },
    ],
    estimatedDuration: '~60 min',
    targetPlayer: 'High rollers who love wild-card poker',
    color: '#eab308',
    icon: 'color-wand-outline',
    emoji: '🎪',
    format: "Joker Hold'em · Featured Event",
    prizeLabel: '1st: 50%  ·  2nd: 30%  ·  3rd: 20%',
    variant: 'joker_holdem',
    capacityMax: 5,
    scheduleIntervalMin: 80,
    scheduleOffsetMin: 32,
  },
};

export function getPrizePool(config: TournamentConfig): number {
  return config.numPlayers * config.buyIn;
}

export const TEXAS_TOURNAMENTS: TournamentType[] = [
  'beginner', 'sitandgo', 'turbo', 'daily', 'highroller', 'nightgrind', 'weekendmajor', 'deepstack', 'hyperturbo',
];
export const SHORT_DECK_TOURNAMENTS: TournamentType[] = ['sd_lounge', 'sd_showdown', 'sd_rush', 'sd_royal'];
export const OMAHA_TOURNAMENTS: TournamentType[] = ['omaha_championship', 'omaha_highroller'];
export const JOKER_TOURNAMENTS: TournamentType[] = ['joker_showdown', 'joker_jackpot'];
export const ALL_TOURNAMENTS: TournamentType[] = [
  ...TEXAS_TOURNAMENTS, ...SHORT_DECK_TOURNAMENTS, ...OMAHA_TOURNAMENTS, ...JOKER_TOURNAMENTS,
];
